// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbUIPageData _tbUIPageData;

        public TbUIPageData TbUIPageData
        {
            get
            {
                return LoadTable(
                    ref _tbUIPageData,
                    AssetKeys.TbuipagedataPath,
                    json => new TbUIPageData(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbUIPageData = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbuipagedataPath);
        }
    }
}
