
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace XFramework
{
public partial class Tables
{
    /// <summary>
    /// UI界面配置表
    /// </summary>
    public TbUIPageData TbUIPageData {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbUIPageData = new TbUIPageData(loader("tbuipagedata"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbUIPageData.ResolveRef(this);
    }
}

}

