
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TbLocalzationKeyData : Luban.BeanBase
{
    public TbLocalzationKeyData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Table = (string)_obj.GetValue("Table");
        Value = (string)_obj.GetValue("Value");
    }

    public static TbLocalzationKeyData DeserializeTbLocalzationKeyData(JToken _buf)
    {
        return new TbLocalzationKeyData(_buf);
    }

    /// <summary>
    /// 多语言表
    /// </summary>
    public readonly string Table;
    /// <summary>
    /// 多语言Key
    /// </summary>
    public readonly string Value;


    public const int __ID__ = -1300207;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Table:" + Table + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

