
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// UI界面配置表
/// </summary>
public partial class TbUIPageData
{
    private readonly System.Collections.Generic.Dictionary<string, UIPageData> _dataMap;
    private readonly System.Collections.Generic.List<UIPageData> _dataList;
    
    public TbUIPageData(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, UIPageData>(_buf.Count);
        _dataList = new System.Collections.Generic.List<UIPageData>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            UIPageData _v;
            _v = global::XFramework.UIPageData.DeserializeUIPageData(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.PageID, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, UIPageData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UIPageData> DataList => _dataList;

    public UIPageData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UIPageData Get(string key) => _dataMap[key];
    public UIPageData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

