
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum UICanvasLayer
    {
        /// <summary>
        /// 最底层
        /// </summary>
        UIBackground = 0,
        /// <summary>
        /// 中层
        /// </summary>
        UIPanel = 1,
    }

} 

