
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace XFramework
{ 
    public enum UIParentLayer
    {
        /// <summary>
        /// 最底层
        /// </summary>
        UIPanel = 0,
        /// <summary>
        /// 中层
        /// </summary>
        UIDialogue = 1,
        /// <summary>
        /// 弹窗层
        /// </summary>
        UIPop = 2,
        /// <summary>
        /// 顶层
        /// </summary>
        UITop = 3,
    }

} 

