
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class UIPageData : Luban.BeanBase
{
    public UIPageData(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        PageID = (string)_obj.GetValue("PageID");
        PagePath = (string)_obj.GetValue("PagePath");
        UIParent = (UIParentLayer)(int)_obj.GetValue("UIParent");
        IsTween = (bool)_obj.GetValue("isTween");
        IsMouseRightHide = (bool)_obj.GetValue("isMouseRightHide");
        Description = (string)_obj.GetValue("Description");
    }

    public static UIPageData DeserializeUIPageData(JToken _buf)
    {
        return new UIPageData(_buf);
    }

    /// <summary>
    /// 界面ID
    /// </summary>
    public readonly string PageID;
    /// <summary>
    /// 界面路径
    /// </summary>
    public readonly string PagePath;
    /// <summary>
    /// 子层级
    /// </summary>
    public readonly UIParentLayer UIParent;
    /// <summary>
    /// 应用默认动画
    /// </summary>
    public readonly bool IsTween;
    /// <summary>
    /// 应用鼠标右键关闭
    /// </summary>
    public readonly bool IsMouseRightHide;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1695317619;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PageID:" + PageID + ","
        + "PagePath:" + PagePath + ","
        + "UIParent:" + UIParent + ","
        + "isTween:" + IsTween + ","
        + "isMouseRightHide:" + IsMouseRightHide + ","
        + "Description:" + Description + ","
        + "}";
    }
}
}

