// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 AddressableKeyGeneratorOdinWindow 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class AssetKeys
    {
        public const string AudioConfigurationPath = "Assets/AddressableAssets/Remote/Configs/Audio/AudioConfiguration.asset";
        public const string XMixerPath = "Assets/AddressableAssets/Remote/Configs/Audio/XMixer.mixer";
        public const string TbuipagedataPath = "Assets/AddressableAssets/Remote/Configs/LubanJson/tbuipagedata.json";
        public const string MusicSourcePath = "Assets/AddressableAssets/Remote/Prefabs/AudioItem/MusicSource.prefab";
        public const string CoinNumberTexUGUIPath = "Assets/AddressableAssets/Remote/Prefabs/DamageNumber/GUI/CoinNumberTexUGUI.prefab";
        public const string FenNumberTexUGUIPath = "Assets/AddressableAssets/Remote/Prefabs/DamageNumber/GUI/FenNumberTexUGUI.prefab";
        public const string PopLoadingUIPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/PopLoadingUI/PopLoadingUI.prefab";
        public const string AtlasCommon314Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_314.png";
        public const string AtlasCommon330Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_330.png";
        public const string AtlasCommon345Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_345.png";
        public const string AtlasCommon346Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_346.png";
        public const string AtlasCommon367Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_367.png";
        public const string AtlasCommon375Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_375.png";
        public const string AtlasCommon376Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/AtlasCommon_376.png";
        public const string ChatGPTImage2026年7月9日112931Path = "Assets/AddressableAssets/Remote/Texture2D/Backgrounds/ChatGPT Image 2026年7月9日 11_29_31.png";
    }
}
